package app.aaps.plugins.sync.asteroidOS

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.AdapterView
import app.aaps.plugins.sync.R
import app.aaps.plugins.sync.databinding.AsteroidosFragmentBinding
import dagger.android.support.DaggerFragment
import java.text.DecimalFormat
import javax.inject.Inject

class AsteroidOSFragment : DaggerFragment() {
    @Inject lateinit var asteroidOSPlugin: AsteroidOSPlugin

    // NOTE: The binding is autogenerated, which is why it is called "AsteroidosFragmentBinding"
    // instead of "AsteroidOSFragmentBinding" - the name is picked by the code autogeneration.
    private var _binding: AsteroidosFragmentBinding? = null

    // NOTE: This property is only valid between onCreateView and onDestroyView.
    private val binding get() = _binding!!

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View =
        AsteroidosFragmentBinding.inflate(inflater, container, false).also { _binding = it }.root

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        binding.asteroidosTimeSeriesTimespan.setParams(
            initValue = asteroidOSPlugin.timeSeriesTimespan.toDouble(),
            minValue = MIN_ASTEROIDOS_TIME_SERIES_TIMESPAN.toDouble(),
            maxValue = MAX_ASTEROIDOS_TIME_SERIES_TIMESPAN.toDouble(),
            step = 1.0,
            formatter = DecimalFormat("0"),
            allowZero = false,
            okButton = null,
            textWatcher = null
        )
        binding.asteroidosTimeSeriesTimespan.setOnValueChangedListener { value ->
            asteroidOSPlugin.timeSeriesTimespan = value.toInt()
        }

        // To determine what visualization type was selected, a second string
        // array exists that contains the IDs. Unfortunately, in Android, it
        // is not possible to associate string array items with IDs directly,
        // so a second array of equal size is the usual way of identifying
        // strings without having to hardcode their content here. This makes
        // it easier later to implement things like localization, since only
        // the actual strings need to be localized, not the ID strings.
        val initialSelectedId = when (asteroidOSPlugin.timeSeriesVisualizationType) {
            TimeSeriesVisualizationType.DOTS -> "id_dots"
            TimeSeriesVisualizationType.LINES -> "id_lines"
        }
        val initialPosition = resources.getStringArray(R.array.asteroidos_time_series_visualization_item_ids).indexOf(initialSelectedId)
        if (initialPosition != -1)
            binding.asteroidosTimeSeriesVisualization.setSelection(initialPosition)
        binding.asteroidosTimeSeriesVisualization.onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
            override fun onItemSelected(
                parent: AdapterView<*>,
                view: View?,
                position: Int,
                id: Long
            ) {
                val ids = resources.getStringArray(R.array.asteroidos_time_series_visualization_item_ids)
                val selectedId = ids[position]

                asteroidOSPlugin.timeSeriesVisualizationType = when (selectedId) {
                    "id_dots" -> TimeSeriesVisualizationType.DOTS
                    "id_lines" -> TimeSeriesVisualizationType.LINES
                    else -> return
                }
            }

            override fun onNothingSelected(parent: AdapterView<*>) {
            }
        }

        binding.asteroidosSendDataButton.setOnClickListener {
            asteroidOSPlugin.sendFullBGData()
        }
    }
}